- name: Instalación de Docker y Docker Compose en Ubuntu Server 18.04 LTS
  hosts: virtual-machine
  vars_files:
    - ../env_variables
  become: true

  tasks:
    - name: Añadir clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker.install | bool

    - name: Agregar el repositorio de Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: true
      when: docker.install | bool

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
      when: docker.install | bool

    - name: Descargar Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      when: docker.install | bool