- name: Create azure infrastructure
  hosts: localhost
  vars_files:
    - ./env_variables
  become: true

  tasks:
    - name: Ejecutar terraform init
      command: terraform init
      when: terraform.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"

    - name: Ejecutar terraform plan 1
      command: terraform plan -var-file="{{terraform.options.tfvars_file}}" --out {{terraform.options.plan_file}}
      when: terraform.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"

    - name: Ejecutar terraform apply
      command: terraform apply "{{terraform.options.plan_file}}"
      when: terraform.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"
      check_mode: false

    # Automation

    - name: Guardar la ip publica del firewall
      shell: terraform output firewall_public_ip | tr -d '"' > ../ansible/software/fw_ip.txt
      when: automation.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"

    - name: Sustituir la ip publica del firewall en el fichero hosts del playbook de software
      shell: sed -i "s/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/$(cat fw_ip.txt)/" hosts
      when: automation.enabled | bool
      args:
        chdir: "{{automation.options.ansible_software_path}}"

    - name: Sustituir la ip publica del firewall en el fichero hosts del playbook de applications
      shell: sed -i "s/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/$(cat fw_ip.txt)/" ../applications/hosts ; rm fw_ip.txt
      when: automation.enabled | bool
      args:
        chdir: "{{automation.options.ansible_software_path}}"

    - name: Guardar el nombre del grupo de recursos
      shell: terraform output resource_group_name | tr -d '"' > ../ansible/software/rgname.txt
      when: automation.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"

    - name: Sustituir el nombre del grupo de recursos en el fichero env_variables
      shell: sed -i "s/\(resource_group_name{{":"}} \)[^ ]*/\1$(cat rgname.txt)/" env_variables ; rm rgname.txt
      when: automation.enabled | bool
      args:
        chdir: "{{automation.options.ansible_software_path}}"

    - name: Guardar el nombre del aks
      shell: terraform output aks_name | tr -d '"' > ../ansible/software/aksname.txt
      when: automation.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"
    
    - name: Sustituir el nombre del aks en el fichero env_variables
      shell: sed -i "s/\(aks_name{{":"}} \)[^ ]*/\1$(cat aksname.txt)/" env_variables ; rm aksname.txt
      when: automation.enabled | bool
      args:
        chdir: "{{automation.options.ansible_software_path}}"

    # vm key permissions

    - name: Proteger la clave privada de la máquina virtual
      shell: chmod 400 private_keys/vm_private_key.pem
      when: terraform.enabled | bool
      args:
        chdir: "{{terraform.options.path}}"